{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "coordination-engine.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coordination-engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "coordination-engine.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.interval }}
    scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
    path: /metrics
{{- end }}
